name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Repository Variable to Lowercase
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:latest, ghcr.io/${{ steps.string.outputs.lowercase }}:${{ github.head_ref || github.ref_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}